[workspace]
resolver = "2"
members = [
    "charting",
    "server", 
    "coinbase-logger",
    "file_server"
]

[workspace.dependencies]
# Common dependencies across workspace members
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
futures = "0.3"
url = "2"
bytes = "1.0"