[package]
name = "tutorial1-window"
version = "0.1.0"
authors = ["Ben Hansen <https://github.com/sotrh>"]
edition = "2018"

[features]
GpuAddressMode = []
react-mode = []

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "tutorial1-window"
path = "src/main.rs"

[dependencies]
cfg-if = "1"
bytemuck = { version = "1.7.3", features = ["derive"] }
winit = { version = "0.30.5", features = ["rwh_05"] }
env_logger = "0.11.5"
log = "0.4.22"
wgpu = { version = "=24.0.5", features = ["webgpu"] }
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
nalgebra-glm = "0.18"
# Force secure versions to fix vulnerabilities
crossbeam-channel = "0.5.15"
js-sys = "0.3.77"
getrandom = { version = "0.2", features = ["js"] }
# For network requests in the browser
reqwasm = "0.5"
futures = "0.3"
futures-intrusive = "0.5.0"
serde_json = "1.0.138"
serde = "1.0.217"
wgpu_text = "=0.9.2"
chrono = "0.4.39"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
web-sys = { version = "0.3.77", features = [
    "Document",
    "Window",
    "Location",
    "UrlSearchParams",
    "Element",
    "WebSocket",
    "BinaryType",
    "ErrorEvent",
    "Performance",
    "Response",
    "ReadableStreamDefaultReader",
    "ReadableStream",
] }
