version: '3.8'

services:
  logger:
    build:
      context: .
      dockerfile: logger/Dockerfile
    container_name: gpu-charts-logger
    ports:
      - "9090:9090"  # Metrics endpoint
      - "8080:8080"  # Health check endpoint
    volumes:
      - ./data:/mnt/md/data
    environment:
      - RUST_LOG=info
      - METRICS_PORT=9090
    restart: unless-stopped
    networks:
      - gpu-charts-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: gpu-charts-server
    ports:
      - "8443:8443"
      - "9091:9091"  # Metrics endpoint
    volumes:
      - ./data:/mnt/md/data
      - ./certs:/certs
    environment:
      - DATA_PATH=/mnt/md/data
      - SSL_CERT_PATH=/certs/cert.pem
      - SSL_PRIVATE_FILE=/certs/key.pem
      - RUST_LOG=info
      - USE_TLS=false
      - METRICS_PORT=9091
    restart: unless-stopped
    depends_on:
      - logger
    networks:
      - gpu-charts-network

networks:
  gpu-charts-network:
    driver: bridge