version: '3.8'

services:
  # Coinbase Logger Service
  coinbase-logger:
    build:
      context: .
      dockerfile: coinbase-logger/Dockerfile
    container_name: coinbase-logger
    restart: unless-stopped
    volumes:
      - coinbase-data:/app/data
    environment:
      - RUST_LOG=info
    networks:
      - gpu-charts-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "coinbase-logger"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # GPU Charts Server
  gpu-charts-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: gpu-charts-server
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      # Mount data directory
      - ${DATA_PATH:-/mnt/md/data}:/data:ro
      # Optional: Mount custom SSL certificates
      # - ./certs:/app/certs:ro
    environment:
      - RUST_LOG=info
      - SSL_CERT_PATH=/app/certs/localhost.crt
      - SSL_KEY_PATH=/app/certs/localhost.key
      - DATA_PATH=/data
      - PORT=8443
    networks:
      - gpu-charts-network
    depends_on:
      - coinbase-logger
    healthcheck:
      test: ["CMD", "timeout", "5s", "bash", "-c", ":> /dev/tcp/127.0.0.1/8443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  coinbase-data:
    driver: local

networks:
  gpu-charts-network:
    driver: bridge