logger:
  data_path: /mnt/HDDs/coinbase_logger
  buffer_size: 8192
  flush_interval_secs: 5
  health_check_port: 8080

exchanges:
  coinbase:
    enabled: true
    ws_endpoint: wss://ws-feed.exchange.coinbase.com
    rest_endpoint: https://api.exchange.coinbase.com
    max_connections: 10
    symbols_per_connection: 50
    reconnect_delay_secs: 1
    max_reconnect_delay_secs: 60
    ping_interval_secs: null

  binance:
    enabled: true
    ws_endpoint: wss://stream.binance.com:9443
    rest_endpoint: https://api.binance.com
    max_connections: 5
    symbols_per_connection: 100
    reconnect_delay_secs: 1
    max_reconnect_delay_secs: 60
    ping_interval_secs: 20

  okx:
    enabled: true
    ws_endpoint: wss://ws.okx.com:8443/ws/v5/public
    rest_endpoint: https://www.okx.com/api/v5
    max_connections: 10
    symbols_per_connection: 100
    reconnect_delay_secs: 1
    max_reconnect_delay_secs: 60
    ping_interval_secs: 30

  kraken:
    enabled: true
    ws_endpoint: wss://ws.kraken.com
    rest_endpoint: https://api.kraken.com/0
    max_connections: 10
    symbols_per_connection: 50
    reconnect_delay_secs: 1
    max_reconnect_delay_secs: 60
    ping_interval_secs: 60

  bitfinex:
    enabled: true
    ws_endpoint: wss://api-pub.bitfinex.com/ws/2
    rest_endpoint: https://api-pub.bitfinex.com/v2
    max_connections: 10
    symbols_per_connection: 15
    reconnect_delay_secs: 1
    max_reconnect_delay_secs: 60
    ping_interval_secs: 15

symbol_mappings:
  mappings_file: "symbol_mappings.yaml"
  auto_discover: true
  equivalence_rules:
    quote_assets:
      - group: USD_EQUIVALENT
        members:
          - USD
          - USDT
          - USDC
          - BUSD
          - DAI
          - TUSD
          - USDP
          - USDD
          - GUSD
          - FRAX
          - LUSD
          - CUSD
          - USTC
          - aUSDC
        primary: USD