logger:
  data_path: "data"
  buffer_size: 8192
  flush_interval_secs: 5

exchanges:
  coinbase:
    enabled: false
    websocket_url: "wss://ws-feed.exchange.coinbase.com"
    symbols:
      - "BTC-USD"
      - "ETH-USD"
      - "XRP-USD"
      - "SOL-USD"
      - "DOGE-USD"

  binance:
    enabled: false
    websocket_url: "wss://stream.binance.com:9443/ws"
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "XRPUSDT"
      - "SOLUSDT"
      - "DOGEUSDT"

  okx:
    enabled: true
    ws_endpoint: "wss://ws.okx.com:8443/ws/v5/public"
    rest_endpoint: "https://www.okx.com/api/v5"
    max_connections: 1
    symbols_per_connection: 5
    max_symbols: 5

  kraken:
    enabled: true
    ws_endpoint: "wss://ws.kraken.com"
    rest_endpoint: "https://api.kraken.com/0/public"
    max_connections: 10
    symbols_per_connection: 50
    max_symbols: 500

  bitfinex:
    enabled: true
    ws_endpoint: "wss://api-pub.bitfinex.com/ws/2"
    rest_endpoint: "https://api-pub.bitfinex.com/v2"
    max_connections: 10
    symbols_per_connection: 30
    max_symbols: 300

symbol_mappings:
  auto_discover: true
  equivalence_rules:
    quote_assets:
      - group: "USD_EQUIVALENT"
        members: ["USDT", "USDC", "BUSD", "USD"]
        primary: "USD"