name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Code Quality and Linting
  lint:
    runs-on: ubuntu-latest
    name: Code Quality
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run TypeScript/React linting
        run: npm run lint
      
      - name: Check Rust formatting (workspace)
        run: cargo fmt --all --check
      
      - name: Run Clippy (WASM crates)
        run: |
          cd crates/wasm-bridge
          cargo clippy --target wasm32-unknown-unknown -- -D warnings
      
      - name: Run Clippy (server)
        run: |
          cd server
          cargo clippy --target x86_64-unknown-linux-gnu -- -D warnings
      
      - name: Run Clippy (logger)
        run: |
          cd logger
          cargo clippy --target x86_64-unknown-linux-gnu -- -D warnings

  # API Server Tests
  server-tests:
    runs-on: ubuntu-latest
    name: Server Tests
    needs: lint
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev
    
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          server/target
        key: ${{ runner.os }}-server-cargo-${{ hashFiles('server/Cargo.lock', 'server/Cargo.toml') }}
    
    - name: Build server
      run: |
        cd server
        cargo build --release
    
    - name: Run server unit and integration tests
      run: |
        cd server
        cargo test --verbose
    
    - name: Generate test coverage report
      run: |
        cd server
        cargo test -- --nocapture

  # Coinbase Logger Tests  
  logger-tests:
    runs-on: ubuntu-latest
    name: Coinbase Logger Tests
    needs: lint
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev
    
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          logger/target
        key: ${{ runner.os }}-logger-cargo-${{ hashFiles('logger/Cargo.lock', 'logger/Cargo.toml') }}
    
    - name: Build logger
      run: |
        cd logger
        cargo build --release
    
    - name: Run logger comprehensive test suite
      run: |
        cd logger
        cargo test --verbose
    
    - name: Run logger test coverage
      run: |
        cd logger
        cargo test -- --nocapture
        
  # Build Validation
  build-validation:
    runs-on: ubuntu-latest
    name: Build Validation
    needs: [lint, frontend-tests, server-tests, logger-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev
    
    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        npm ci
        rm -rf web/node_modules || true
    
    - name: Build all components
      run: |
        # Build WASM module
        npm run build:wasm
        
        # Build frontend
        cd web
        npm run build
        cd ..
        
        # Build server
        npm run build:server
        
        # Build logger
        npm run build:logger
    
    - name: Validate build artifacts
      run: |
        echo "=== WASM Build Artifacts ==="
        ls -la web/pkg/
        
        echo "=== Frontend Build Artifacts ==="
        ls -la web/dist/
        
        echo "=== Server Build Artifacts ==="
        ls -la target/x86_64-unknown-linux-gnu/release/
        
        echo "=== Coinbase Logger Build Artifacts ==="
        ls -la target/x86_64-unknown-linux-gnu/release/
    
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          web/pkg/
          web/dist/
          target/x86_64-unknown-linux-gnu/release/ultra_low_latency_server_chunked_parallel
          target/x86_64-unknown-linux-gnu/release/logger
        retention-days: 30