name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install dependencies
      run: |
        cd web
        npm ci
    
    - name: Build WASM module
      run: |
        cd web
        npm run build:wasm
    
    - name: Install Playwright Browsers
      run: |
        cd web
        npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: |
        cd web
        npm run test
    
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: web/playwright-report/
        retention-days: 30
    
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: web/test-results/
        retention-days: 30

  # Separate job for browser compatibility testing
  browser-compatibility:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Install dependencies
      run: |
        cd web
        npm ci
    
    - name: Build WASM module
      run: |
        cd web
        npm run build:wasm
    
    - name: Install Playwright Browsers
      run: |
        cd web
        npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests on ${{ matrix.browser }}
      run: |
        cd web
        npx playwright test --project=${{ matrix.browser }}
    
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: web/playwright-report/
        retention-days: 30